name = "coly"
uuid = "b9ff8d13-d7e1-45e6-8683-63ca9ecaa54e"
authors = ["AaronMarcusDev <aaronmarcus2007@gmail.com>"]
version = "0.1.0"

[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
